using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using Swarms.Core;

namespace Swarms.Models.Agent;

[JsonConverter(typeof(ModelConverter<AgentRunResponse, AgentRunResponseFromRaw>))]
public sealed record class AgentRunResponse : ModelBase
{
    /// <summary>
    /// A description of the agent or completion.
    /// </summary>
    public string? Description
    {
        get { return ModelBase.GetNullableClass<string>(this.RawData, "description"); }
        init { ModelBase.Set(this._rawData, "description", value); }
    }

    /// <summary>
    /// The unique identifier for the agent completion.
    /// </summary>
    public string? JobID
    {
        get { return ModelBase.GetNullableClass<string>(this.RawData, "job_id"); }
        init { ModelBase.Set(this._rawData, "job_id", value); }
    }

    /// <summary>
    /// The name of the agent.
    /// </summary>
    public string? Name
    {
        get { return ModelBase.GetNullableClass<string>(this.RawData, "name"); }
        init { ModelBase.Set(this._rawData, "name", value); }
    }

    /// <summary>
    /// The outputs generated by the agent.
    /// </summary>
    public JsonElement? Outputs
    {
        get { return ModelBase.GetNullableStruct<JsonElement>(this.RawData, "outputs"); }
        init
        {
            if (value == null)
            {
                return;
            }

            ModelBase.Set(this._rawData, "outputs", value);
        }
    }

    /// <summary>
    /// Indicates whether the agent completion was successful.
    /// </summary>
    public bool? Success
    {
        get { return ModelBase.GetNullableStruct<bool>(this.RawData, "success"); }
        init { ModelBase.Set(this._rawData, "success", value); }
    }

    /// <summary>
    /// The temperature setting used for the agent's response generation.
    /// </summary>
    public double? Temperature
    {
        get { return ModelBase.GetNullableStruct<double>(this.RawData, "temperature"); }
        init { ModelBase.Set(this._rawData, "temperature", value); }
    }

    /// <summary>
    /// The timestamp when the agent completion was created.
    /// </summary>
    public string? Timestamp
    {
        get { return ModelBase.GetNullableClass<string>(this.RawData, "timestamp"); }
        init { ModelBase.Set(this._rawData, "timestamp", value); }
    }

    /// <summary>
    /// Usage statistics or metadata for the agent completion.
    /// </summary>
    public IReadOnlyDictionary<string, JsonElement>? Usage
    {
        get
        {
            return ModelBase.GetNullableClass<Dictionary<string, JsonElement>>(
                this.RawData,
                "usage"
            );
        }
        init { ModelBase.Set(this._rawData, "usage", value); }
    }

    public override void Validate()
    {
        _ = this.Description;
        _ = this.JobID;
        _ = this.Name;
        _ = this.Outputs;
        _ = this.Success;
        _ = this.Temperature;
        _ = this.Timestamp;
        _ = this.Usage;
    }

    public AgentRunResponse() { }

    public AgentRunResponse(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = [.. rawData];
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    AgentRunResponse(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = [.. rawData];
    }
#pragma warning restore CS8618

    public static AgentRunResponse FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class AgentRunResponseFromRaw : IFromRaw<AgentRunResponse>
{
    public AgentRunResponse FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        AgentRunResponse.FromRawUnchecked(rawData);
}
