using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using Swarms.Core;

namespace Swarms.Models.Agent.Batch;

[JsonConverter(typeof(ModelConverter<BatchRunResponse, BatchRunResponseFromRaw>))]
public sealed record class BatchRunResponse : ModelBase
{
    /// <summary>
    /// The unique identifier for the agent batch completion.
    /// </summary>
    public string? BatchID
    {
        get { return ModelBase.GetNullableClass<string>(this.RawData, "batch_id"); }
        init { ModelBase.Set(this._rawData, "batch_id", value); }
    }

    /// <summary>
    /// The execution time of the agent batch completion.
    /// </summary>
    public double? ExecutionTime
    {
        get { return ModelBase.GetNullableStruct<double>(this.RawData, "execution_time"); }
        init { ModelBase.Set(this._rawData, "execution_time", value); }
    }

    /// <summary>
    /// The outputs generated by the agent.
    /// </summary>
    public JsonElement? Results
    {
        get { return ModelBase.GetNullableStruct<JsonElement>(this.RawData, "results"); }
        init
        {
            if (value == null)
            {
                return;
            }

            ModelBase.Set(this._rawData, "results", value);
        }
    }

    /// <summary>
    /// The timestamp when the agent batch completion was created.
    /// </summary>
    public string? Timestamp
    {
        get { return ModelBase.GetNullableClass<string>(this.RawData, "timestamp"); }
        init { ModelBase.Set(this._rawData, "timestamp", value); }
    }

    /// <summary>
    /// The total number of requests in the batch.
    /// </summary>
    public long? TotalRequests
    {
        get { return ModelBase.GetNullableStruct<long>(this.RawData, "total_requests"); }
        init { ModelBase.Set(this._rawData, "total_requests", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.BatchID;
        _ = this.ExecutionTime;
        _ = this.Results;
        _ = this.Timestamp;
        _ = this.TotalRequests;
    }

    public BatchRunResponse() { }

    public BatchRunResponse(BatchRunResponse batchRunResponse)
        : base(batchRunResponse) { }

    public BatchRunResponse(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = [.. rawData];
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    BatchRunResponse(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = [.. rawData];
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="BatchRunResponseFromRaw.FromRawUnchecked"/>
    public static BatchRunResponse FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class BatchRunResponseFromRaw : IFromRaw<BatchRunResponse>
{
    /// <inheritdoc/>
    public BatchRunResponse FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        BatchRunResponse.FromRawUnchecked(rawData);
}
